//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy_History
    {
        public int ID_Buy_History { get; set; }
        public System.DateTime Buy_Date_History { get; set; }
        public string Buy_Plus_History { get; set; }
        public string Buy_Money_History { get; set; }
        public int Users_Buy_ID_History { get; set; }
        public int Contractor_ID_History { get; set; }
        public int Request_ID_History { get; set; }
        public System.DateTime Date_Create { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual Request Request { get; set; }
        public virtual Users Users { get; set; }
    }
}
