//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID_Order { get; set; }
        public System.DateTime Order_Date { get; set; }
        public string Order_Amount { get; set; }
        public int Order_Number { get; set; }
        public string Order_Status { get; set; }
        public int Service_Delivery_Assembly_ID { get; set; }
        public int Tovar_ID { get; set; }
        public int Users_ID { get; set; }
    
        public virtual Service_Delivery_Assembly Service_Delivery_Assembly { get; set; }
        public virtual Tovar Tovar { get; set; }
        public virtual Users Users { get; set; }
    }
}
