//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int ID_Pay { get; set; }
        public System.DateTime Pay_Date { get; set; }
        public string Pay_Money { get; set; }
        public int Users_Pay_ID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
