//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_History
    {
        public int ID_Request_History { get; set; }
        public string Request_Desc_History { get; set; }
        public System.DateTime Request_Date_Start_History { get; set; }
        public Nullable<System.DateTime> Request_Date_End_History { get; set; }
        public string Request_Status_History { get; set; }
        public int Users_Request_ID_History { get; set; }
        public System.DateTime Date_Create { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
