//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad_History
    {
        public int ID_Sklad_History { get; set; }
        public string Sklad_Address_History { get; set; }
        public string Sklad_Sity_History { get; set; }
        public string Sklad_Name_History { get; set; }
        public System.DateTime Date_Create { get; set; }
    }
}
