//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        public string Sotrudniki_Last_Name { get; set; }
        public string Sotrudniki_Name { get; set; }
        public string Sotrudniki_Education { get; set; }
        public string Sotrudniki_Experience { get; set; }
        public string Sotrudniki_Age { get; set; }
        public string Sotrudniki_Language { get; set; }
        public string Sotrudniki_Middle_Name { get; set; }
        public string Sotrudniki_Money { get; set; }
        public int Users_Sotrudniki_ID { get; set; }
        public int Roles_ID { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Users Users { get; set; }
    }
}
