//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID_Tovar { get; set; }
        public string Tovar_Image { get; set; }
        public string Tovar_Name { get; set; }
        public string Tovar_Colour { get; set; }
        public string Tovar_Size { get; set; }
        public string Tovar_Desc { get; set; }
        public string Tovar_Country { get; set; }
        public int Sklad_ID { get; set; }
        public int Model_ID { get; set; }
        public int Sort_ID { get; set; }
    
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Sklad Sklad { get; set; }
        public virtual Sort Sort { get; set; }
    }
}
